# -*- coding: utf-8 -*-
"""Analise_Exploratoria_Enem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zL9H7REG4v8eWi4IFdRiWNEPQKszmoDV
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd 
from google.colab import drive
import numpy as np  
import matplotlib.pyplot as plt 
# % matplotlib inline
import seaborn as sns

drive.mount('/content/drive')

df_reduzida = pd.read_sas('/content/drive/My Drive/Enem/ENEM_Amostra_10_reduzida.sas7bdat',format='sas7bdat',encoding='Latin1')
df_reduzida.head()

df_reduzida[['ANO']].value_counts()

df_reduzida.info()

"""# ANÁLISE EXPLORÁTORIA - NOTA DE MATEMÁTICA

Foi realizado uma análise da nota de matemática dos estudantes que fizeram o Enem a fim de responder as seguintes perguntas: 

- Qual o comportamento da Nota de Matemática?
- Qual foi a nota média em matemática dos estudantes em cada estado?
- Qual foi a nota média em matemática dos estudantes em cada tipo de escola? 

- Existe correlação entre as notas de matemática com as outras notas?

## Qual o comportamento da nota de matemática?
"""

df_reduzida.describe()

"""Nesse trabalho foi analisado as notas de 1.020.953 estudantes que realizaram o Exame Nacional do Ensino Médio (ENEM) entre 2017 a 2019. A média das notas de matemática desses estudantes foi 506,84 pontos. No intervalo entre 0 pontos, nota mínima entre os estudantes analisados, e 994,40 pontos, nota máxima de matemática entre os estudantes analisados, as notas variaram em média 142,73 pontos.

25% dos estudantes tiraram notas entre 0 e 435,60 pontos. 50% dos estudantes tiraram notas abaixo de 502 pontos. 75% dos estudantes analisados tiraram notas abaixo de 589,3 pontos e 25% dos estudantes tiraram notas entre 589,4 e 994,40 pontos. 
"""

589.3-435.6

589.3-(1.5*(589.3-435.6))
589.3+(1.5*(589.3-435.6))

fig = plt.figure(figsize =(10, 7))
ax = fig.add_subplot(111)
bp = ax.boxplot(df_reduzida['NU_NOTA_MT'], patch_artist =True,
                notch ='True', vert = 1)
bp['boxes'][0].set_facecolor('#A72759')
bp['whiskers'][0].set(linewidth = 2,linestyle =":")
bp['whiskers'][1].set(linewidth = 2,linestyle =":")
bp['caps'][0].set(linewidth = 2)
bp['caps'][1].set(linewidth = 2)
bp['medians'][0].set(color ='#89E150',linewidth = 2)
bp['fliers'][0].set(marker ='D',color ='#A4FF6A',alpha = 0.5)
ax.set_xticklabels(['Nota de Matemática'])
plt.title("Box Plot da Nota de Matemática")
ax.get_xaxis().tick_bottom()
ax.get_yaxis().tick_left()
plt.show(bp)

fig = plt.figure(figsize =(10, 7))
plt.title('Frequência da Nota de Matemática do Enem')
plt.xlabel('Nota de Matemática')
plt.ylabel('Frequência Absoluta')
plt.hist(df_reduzida['NU_NOTA_MT'], 50, color='#900C3F', alpha=0.7,edgecolor='white')
plt.show()

df_reduzida['NU_NOTA_MT'].value_counts()

"""No gráfico da frequência é possível identificar que 37.469 alunos tiraram notas próximo de 0. Também é possível identificar que a nota mais frequente entre os estudantes foi 446.4 pontos. Com auxílio do gráfico é possível ratificar o que foi falado acima, como por exemplo, como há uma queda da quantidade de estudantes a medida que as notas crescem logo após os 600 pontos, ratificando que 25% dos estudantes obtiveram notas acima de 589,4.

## Qual foi a nota média em matemática dos estudantes em cada estado?
"""

df_reduzida[['SG_UF_RESIDENCIA']].mode()

df_residencia = df_reduzida.groupby(by=['SG_UF_RESIDENCIA'])['NU_NOTA_MT'].mean().reset_index(name='media')

df_residencia = df_residencia.sort_values('media',ascending=False)
df_residencia.head()

"""Em relação a nota média, os estados que mais se destacaram foram estados do Sul e Sudeste do país: Santa Catarina com 532,7 pontos, Minas Gerais com 527,94 pontos, São Paulo com 527,78 pontos, Rio de Janeiro com 524,04 pontos e o Espiríto Santo com 520 pontos. Os 5 estados que tiveram as piores médias foram estados do Norde e Nordeste do país: Amapá com 468,68 pontos, Acre com 469,53 pontos, Amazonas com 471,59 pontos, Maranhão com 472,55 pontos e o Pará com 476,29 pontos. A distância das notas médias do Amapá, que obteve a pior nota média entre os estados, e Santa Catarina, com a melhor nota entre os estados, foi de 64.02 pontos.  """

fig = plt.figure(figsize =(10, 7))
plt.title('Média das Notas de Matemática por UF')
plt.ylabel('Nota de Matemática')
plt.xlabel('Unidade Federativa')
plt.bar(df_residencia['SG_UF_RESIDENCIA'],df_residencia['media'], color='#900C3F', alpha=0.7,edgecolor='white')
plt.show()

"""## Qual foi a nota média em matemática dos estudantes em cada tipo de escola?"""

df_reduzida[['TIPO_ESCOLA']].value_counts()

df_escola = df_reduzida.groupby(by=['TIPO_ESCOLA'])['NU_NOTA_MT'].mean().reset_index(name='media')

df_escola=df_escola.drop(index=1)
df_escola.head()

"""Em relação ao tipo de escola frequentado pelo estudante, estudantes que frequentaram escolas no exterior tiveram a melhor média na nota de matemática, com 618.89 pontos, os estudantes que frequentaram o ensino privado no país obtiveram a média 574,28 na nota de matemática e os estudantes da escola pública obtiveram a menor média da nota de matemática, 487.31 pontos.

OBS: 665.924 estudantes não responderam qual o tipo de escola frequentou, o que corresponde a 65.25% dos estudantes analisados
"""

665924/1020953

fig = plt.figure(figsize =(10, 7))
plt.title('Média da Nota de Matemática por Tipo de Escola')
plt.ylabel('Nota de Matemática')
plt.xlabel('Tipo de Escola')
plt.bar(df_escola['TIPO_ESCOLA'],df_escola['media'], color='#900C3F', alpha=0.7,edgecolor='white')
plt.show()

"""## Existe correlação entre as notas de matemática com as outras notas?"""

df = df_reduzida[['NU_IDADE','NU_NOTA_CN','NU_NOTA_CH','NU_NOTA_LC','NU_NOTA_MT','NU_NOTA_REDACAO']]
df.head()



cor = df.corr()
cor = cor[['NU_NOTA_MT']]
cor = cor.drop(index='NU_NOTA_MT')
cor.head()

plt.figure(figsize=(16, 6))
matrix = np.triu(cor)
heatmap = sns.heatmap(cor, vmin=-1, vmax=1, annot=True, cmap = "RdBu_r")
heatmap.set_title('Correlação entre as variáveis', fontdict={'fontsize':18}, pad=12);

"""A correlação entre as notas de Linguagens e Código, Ciências Humanas, Ciências da Natureza e Redação com a nota de matemática apresenta uma baixa correlação, o que indica que as notas de Linguagens e Código, Ciências Humanas, Ciências da Natureza e Redação não influenciam tanto na nota de Matemática. Em relação a essas notas, a nota de Redação é a que apresenta uma correlação mais alta, de 0,34, contudo ainda é uma correlação muito baixa, por isso não apresenta uma influência na nota de Matemática. A correlação entre a idade e a nota de Matématica é negativa, o que indicaria que quanto mais novo o estudante é, melhores são as suas notas, porém a correlação é muito baixa, -0,096, por isso não podemos afirmar isso, pois a idade também não influencia nas notas de matemática."""

import matplotlib.pyplot as plt
import numpy as np

figure, axis = plt.subplots(2, 2,figsize =(10, 7))

  
axis[0, 0].scatter(df['NU_NOTA_CH'],df['NU_NOTA_MT'], color='#900C3F', alpha=0.7,edgecolor='white')
axis[0, 0].set_title("Nota de Ciências Humanas")

axis[0, 1].scatter(df['NU_NOTA_CN'],df['NU_NOTA_MT'], color='#900C3F', alpha=0.7,edgecolor='white')
axis[0, 1].set_title('Nota de Ciências da Natureza')
  
axis[1, 0].scatter(df['NU_NOTA_LC'],df['NU_NOTA_MT'], color='#900C3F', alpha=0.7,edgecolor='white')
axis[1, 0].set_title('Nota de Linguagens e Códigos')
  
axis[1, 1].scatter(df['NU_NOTA_REDACAO'],df['NU_NOTA_MT'], color='#900C3F', alpha=0.7,edgecolor='white')
axis[1, 1].set_title('Nota de Redação')


#plt.ylabel('Nota de Matemática')
#plt.title('Média da Nota de Matemática por Tipo de Escola')
plt.show()

"""Esses gráficos apresentam diagramas de dispersão das notas em relação a nota de matemática (eixo y de cada gráfico).

Observando o diagrama de dispersão da nota de Linguagens e Códigos (LC) com a nota de Matemática (MT), constata-se que um conjunto de alunos teve notas muito baixa em LC e em MT, outro conjunto tiraram notas muito baixas em MT, entretanto suas notas de LC foram relativamente positivas, outro conjunto teve notas muito baixas em LC, contudo suas notas em MT foram relativamente boas. Olhando a parte central do diagrama, observa-se que um grupo majoritário de estudantes tiveram notas acima de 300 pontos em LC e MT. Pode-se observar que o grupo de alunos que tirou, por exemplo, 400 pontos, varia entre 380 pontos em MT até notas acima dos 800 pontos, portanto a variabilidade da outra nota em um determinado ponto é alta. O mesmo vale para as notas de MT em comparação com as de LC. Em relação ao diagrama de dispersão da nota de Ciências Humanas (CH) e MT, pode-se dizer que o comportamento é semelhante ao diagrama de dispersão de LC. 

Observando o diagrama de dispersão da nota de Ciências da Natureza (CN) e MT, constata-se que um conjunto de alunos teve notas muito baixa em CN e em MT, outro conjunto tiraram notas muito baixas em MT, entretanto suas notas de CN foram relativamente positivas, outro conjunto teve notas muito baixas em CN, contudo suas notas em MT foram relativamente boas. Olhando a parte central do diagrama, observa-se que um grupo majoritário de estudantes tiveram notas acima de 300 pontos em CN e MT. Pode-se observar que o grupo de alunos que tirou 800 pontos em CN obteve notas alta em MT, acima de 700 pontos, portanto, com a exceção do grupo que obteve 0 em MT e notas altas em CN, pode-se dizer que estudantes que obtiveram notas altas em CN, tiram notas altas em MT.

Observando o diagrama de dispersão da nota de Redação com a nota de MT, constata-se que existe o conjunto de estudantes que tiveram notas muito baixas em MT, tem uma variabilidade muito grande em relação as notas de Redação, pois alguns tiraram notas muito baixas, outros tiraram notas razoavelmente boas e outros tiraram notas excelentes. Em relação ao grupo majoritário, percebe-se que alunos que tiraram notas de Redação entre 0 e 200 pontos, não tiveram um bom desempenho em matemática, ficando com notas entre 400 e 600 pontos. A medida que a nota de Redação aumenta, aumenta, também, a variabilidade das notas de MT. Notas de Redação próximas de 1000 pontos, tiveram estudantes que tiraram notas entre 300 pontos e próximas de 1000 pontos, sendo assim tiveram uma alta variabilidade. 

"""